AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  LambdaCodeSourceBucket:
    Type: "String"
  CognitoUserPoolArn:
    Type: "String"
  CognitoAdminPoolArn:
    Type: "String"
  ReportsDomainName:
    Type: "String"
    Default: "reports"
  ReportsDomainMasterUserName:
    Type: "String"
  ReportsDomainMasterUserPassword:
    Type: "String"
  ReportsTableName:
    Type: "String"
    Default: "reports"
  PhotosBucketName:
    Type: "String"
    Default: "cu-fixit-photos"
  ProcessReportQueueName:
    Type: "String"
    Default: "process-report-queue"
  DetectKeywordsQueueName:
    Type: "String"
    Default: "detect-key-phrases-queue"

Resources:
  ReportsDomain:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      DomainName: !Ref "ReportsDomainName"
      ClusterConfig:
        InstanceType: "t3.small.search"
        InstanceCount: 1
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: "gp2"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: !Sub "arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/${ReportsDomainName}/*"
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: !Ref "ReportsDomainMasterUserName"
          MasterUserPassword: !Ref "ReportsDomainMasterUserPassword"

  ReportsTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref "ReportsTableName"
      AttributeDefinitions:
        - AttributeName: "reportID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "reportID"
          KeyType: "HASH"
      BillingMode: "PROVISIONED"
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: "NEW_IMAGE"

  ReportsTableWriteCapacityScalableTarget:
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    DependsOn: "ReportsTable"
    Properties:
      MaxCapacity: 5
      MinCapacity: 1
      ResourceId: !Sub "table/${ReportsTableName}"
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable"
      ScalableDimension: "dynamodb:table:WriteCapacityUnits"
      ServiceNamespace: "dynamodb"

  ReportsTableWriteScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties:
      PolicyName: !Sub "${ReportsTableName}-write-scaling-policy"
      PolicyType: "TargetTrackingScaling"
      ScalingTargetId: !Ref "ReportsTableWriteCapacityScalableTarget"
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: "DynamoDBWriteCapacityUtilization"
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        TargetValue: 80

  ReportsTableReadCapacityScalableTarget:
    Type: "AWS::ApplicationAutoScaling::ScalableTarget"
    DependsOn: "ReportsTable"
    Properties:
      MaxCapacity: 5
      MinCapacity: 1
      ResourceId: !Sub "table/${ReportsTableName}"
      RoleARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/aws-service-role/dynamodb.application-autoscaling.amazonaws.com/AWSServiceRoleForApplicationAutoScaling_DynamoDBTable"
      ScalableDimension: "dynamodb:table:ReadCapacityUnits"
      ServiceNamespace: "dynamodb"

  ReportsTableReadScalingPolicy:
    Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
    Properties:
      PolicyName: !Sub "${ReportsTableName}-read-scaling-policy"
      PolicyType: "TargetTrackingScaling"
      ScalingTargetId: !Ref "ReportsTableReadCapacityScalableTarget"
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: "DynamoDBReadCapacityUtilization"
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
        TargetValue: 80

  PhotosBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Ref "PhotosBucketName"
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "*"
            AllowedMethods:
              - "GET"
              - "POST"
            AllowedHeaders:
              - "*"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*"
            Function: !GetAtt "LambdaStack.Outputs.DetectPhotoLabelsLambdaArn"

  ProcessReportQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Ref "ProcessReportQueueName"

  DetectKeywordsQueue:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: !Ref "DetectKeywordsQueueName"

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "lambda.yaml"
      Parameters:
        StackName: !Ref "AWS::StackName"
        LambdaCodeSourceBucket: !Ref "LambdaCodeSourceBucket"
        ReportsDomainEndpoint: !GetAtt "ReportsDomain.DomainEndpoint"
        ReportsTableName: !Ref "ReportsTableName"
        ReportsTableStreamArn: !GetAtt "ReportsTable.StreamArn"
        PhotosBucketName: !Ref "PhotosBucketName"
        ProcessReportQueueArn: !GetAtt "ProcessReportQueue.Arn"
        ProcessReportQueueUrl: !GetAtt "ProcessReportQueue.QueueUrl"
        DetectKeywordsQueueArn: !GetAtt "DetectKeywordsQueue.Arn"
        DetectKeywordsQueueUrl: !GetAtt "DetectKeywordsQueue.QueueUrl"

  ApiStack:
    Type: "AWS::CloudFormation::Stack"
    DependsOn: "LambdaStack"
    Properties:
      TemplateURL: "api.yaml"
      Parameters:
        CognitoUserPoolArn: !Ref "CognitoUserPoolArn"
        CognitoAdminPoolArn: !Ref "CognitoAdminPoolArn"
        PostReportLambdaArn: !GetAtt "LambdaStack.Outputs.PostReportLambdaArn"
        SearchReportUserLambdaArn: !GetAtt "LambdaStack.Outputs.SearchReportUserLambdaArn"
        SearchReportAdminLambdaArn: !GetAtt "LambdaStack.Outputs.SearchReportAdminLambdaArn"

Outputs:
  ApiId:
    Description: "API ID"
    Value: !GetAtt "ApiStack.Outputs.ApiId"
