AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  StackName:
    Type: "String"
  MasterUserName:
    Type: "String"
  MasterUserPassword:
    Type: "String"

Resources:
  Domain:
    Type: "AWS::OpenSearchService::Domain"
    Properties:
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: !Sub "arn:${AWS::Partition}:es:${AWS::Region}:${AWS::AccountId}:domain/${StackName}-domain/*"
      AdvancedSecurityOptions:
        Enabled: true
        InternalUserDatabaseEnabled: true
        MasterUserOptions:
          MasterUserName: !Ref "MasterUserName"
          MasterUserPassword: !Ref "MasterUserPassword"
      ClusterConfig:
        InstanceType: "t3.small.search"
        InstanceCount: 1
      DomainEndpointOptions:
        EnforceHTTPS: true
      DomainName: !Sub "${StackName}-domain"
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 10
        VolumeType: "gp2"
      EncryptionAtRestOptions:
        Enabled: true
        KmsKeyId: !Ref "EncryptionKey"
      NodeToNodeEncryptionOptions:
        Enabled: true

  EncryptionKey:
    Type: "AWS::KMS::Key"
    Properties:
      Enabled: true
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:CreateGrant
              - kms:DescribeKey
            Resource: "*"
            Condition:
              StringEquals:
                kms:ViaService: !Sub "es.${AWS::Region}.amazonaws.com"
                kms:CallerAccount: !Ref AWS::AccountId
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: "*"
            Resource: "*"
          - Effect: Allow
            Principal:
              Service: es.amazonaws.com
            Action:
              - kms:Describe*
              - kms:Get*
              - kms:List*
            Resource: "*"

Outputs:
  DomainEndpoint:
    Value: !GetAtt "Domain.DomainEndpoint"
